name: Tests

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]

    env:
      GITHUB_PUBLIC_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install


      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          bb: 'latest'

      - name: Run cli tests
        run: npm run tests

      - name: Verify example/test html dependencies are up to date
        if: matrix.os == 'ubuntu-latest'
        run: |
          DIRS="./examples ./test/scittlets"
          npm run updateLocalHtmlFiles ./catalog.json $DIRS

          for dir in $DIRS; do
            echo -e "\n:test.yml/verifying.. $dir"
            if ! git diff --quiet -w HEAD -- $dir; then
              git --no-pager diff -w HEAD -- $dir
              echo -e "\nHTML dependencies in $dir are out of sync with the catalog."
              echo "Please update them and try again. Exiting.\n"
              exit 1
            fi
          done

          HTMLS="index.html scittlets.html templates.html"
          bb scripts/pages_generate.clj

          for html in $HTMLS; do
            echo -e "\n:test.yml/html-verifying.. $html"
            if ! git diff --quiet -w HEAD -- $html; then
              git --no-pager diff -w HEAD -- $html
              echo -e "\nHTML file $html is out of sync with the selmer templates."
              echo "Please update them and try again. Exiting.\n"
              exit 1
            fi
          done
          
