name: Tests

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install

      - name: Run cli tests
        run: npm run tests

      - name: Verify example/test html dependencies are up to date
        if: matrix.os == 'ubuntu-latest'
        run: |
          DIRS="./examples ./test/scittlets"
          npm run updateLocalHtmlFiles $DIRS

          for dir in $DIRS; do
            echo -e "\n:test.yml/verifying.. $dir"
            if ! git diff --quiet -w HEAD -- $dir; then
              git --no-pager diff -w HEAD -- $dir
              echo -e "\nHTML dependencies in $dir are out of sync with the catalog."
              echo "Please update them and try again. Exiting.\n"
              exit 1
            fi
          done
